### ISSUE TITLE
ODM partition size reduced after restore

### ISSUE THREAD

**Issue by bober10113** [3arthur6/android_device_samsung_crownlte#2]
Hello,

im using an unofficial  build:
https://forum.xda-developers.com/galaxy-note-9/development/recovery-twrp-galaxy-note-9-t3929901/

reason why im reporting it here is they have referenced this git. 

the problem im having is that the ODM partition on a n960n ltecrown device gets reduced from 143mb to 129mb:

https://forum.xda-developers.com/showpost.php?p=80372449&postcount=211

**Comment by 3arthur6** [comment]
Not an issue, and not the right place.
Stop loosing your time and mine.

**Comment by bober10113** [comment]
wow it got fixed! 


...lol
